In [3]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

In [5]:
df =  pd.read_csv("/content/processed_data.txt", index_col=0)

df.dropna(subset=['PCA1', 'PCA2', 'PCA3', 'PCA4', 'PCA5'], inplace=True)

df.reset_index(drop=True, inplace=True)

In [6]:
df.head()

,track_id,artists,album_name,track_name,popularity,track_genre,duration_min,PCA1,PCA2,PCA3,PCA4,PCA5
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,0.73,Folk,3.84,-1.100515,-0.431883,-0.094871,0.094938,0.005738
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,0.55,Folk,2.49,-1.565618,0.467778,-0.402545,-0.207976,-0.144959
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,0.57,Folk,3.51,-1.524470,-0.076150,0.056276,-0.373241,-0.283572
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,0.71,Folk,3.37,1.855022,0.992264,-0.475583,-0.370995,-0.165991
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,0.82,Folk,3.31,-0.104338,0.185106,-0.144287,-0.242401,-0.246385

In [7]:
#features to compare
features = df[['PCA1', 'PCA2', 'PCA3', 'PCA4', 'PCA5']]

In [8]:
features.head()

       PCA1      PCA2      PCA3      PCA4      PCA5
0 -1.100515 -0.431883 -0.094871  0.094938  0.005738
1 -1.565618  0.467778 -0.402545 -0.207976 -0.144959
2 -1.524470 -0.076150  0.056276 -0.373241 -0.283572
3  1.855022  0.992264 -0.475583 -0.370995 -0.165991
4 -0.104338  0.185106 -0.144287 -0.242401 -0.246385

In [9]:
def get_score_from_pair(pair):
    return pair[1]

def get_cosine_recommendations(track_name, df, sim_matrix, n=5):


    try:
        song_row_number = df[df['track_name'] == track_name].index[0]
    except IndexError:
        return f"Song '{track_name}' not found."

    all_scores = sim_matrix[song_row_number]

    scores_with_index = []
    for song_index, score in enumerate(all_scores):
        scores_with_index.append( (song_index, score) )

    sorted_scores = sorted(scores_with_index, key=get_score_from_pair, reverse=True)

    top_n_scores = sorted_scores[1:n+1]

    recommended_song_indices = []
    for pair in top_n_scores:
        song_index = pair[0]
        recommended_song_indices.append(song_index)

    final_recommendations = df.iloc[recommended_song_indices]

    return final_recommendations[['track_name', 'artists', 'track_genre']]

In [ ]:
print("Calculating cosine similarity matrix")

cosine_sim_matrix = cosine_similarity(features, features)

print("Matrix calculation complete.")

Calculating cosine similarity matrix... (This may take a moment)